# Generated by Django 5.0.4 on 2024-04-20 08:23

import autoslug.fields
import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_url', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('discription', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('profile_pic', models.ImageField(blank=True, upload_to='user')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_url', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='title', unique=True)),
                ('dicription', models.TextField(blank=True)),
                ('featured_image', models.ImageField(upload_to='uploads')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, max_length=1000)),
                ('tag_2', models.CharField(blank=True, max_length=1000)),
                ('tag_3', models.CharField(blank=True, max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.category')),
            ],
        ),
    ]
